/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToDoIndexRouteImport } from './routes/toDo/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as QuizStartIndexRouteImport } from './routes/quizStart/index'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GalleryImageIdRouteImport } from './routes/gallery/$imageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToDoIndexRoute = ToDoIndexRouteImport.update({
  id: '/toDo/',
  path: '/toDo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizStartIndexRoute = QuizStartIndexRouteImport.update({
  id: '/quizStart/',
  path: '/quizStart/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryImageIdRoute = GalleryImageIdRouteImport.update({
  id: '/gallery/$imageId',
  path: '/gallery/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/gallery': typeof GalleryIndexRoute
  '/game': typeof GameIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/quizStart': typeof QuizStartIndexRoute
  '/shop': typeof ShopIndexRoute
  '/toDo': typeof ToDoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/gallery': typeof GalleryIndexRoute
  '/game': typeof GameIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/quizStart': typeof QuizStartIndexRoute
  '/shop': typeof ShopIndexRoute
  '/toDo': typeof ToDoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/gallery/': typeof GalleryIndexRoute
  '/game/': typeof GameIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/quizStart/': typeof QuizStartIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/toDo/': typeof ToDoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery/$imageId'
    | '/gallery'
    | '/game'
    | '/quiz'
    | '/quizStart'
    | '/shop'
    | '/toDo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery/$imageId'
    | '/gallery'
    | '/game'
    | '/quiz'
    | '/quizStart'
    | '/shop'
    | '/toDo'
  id:
    | '__root__'
    | '/'
    | '/gallery/$imageId'
    | '/gallery/'
    | '/game/'
    | '/quiz/'
    | '/quizStart/'
    | '/shop/'
    | '/toDo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryImageIdRoute: typeof GalleryImageIdRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  GameIndexRoute: typeof GameIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  QuizStartIndexRoute: typeof QuizStartIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ToDoIndexRoute: typeof ToDoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toDo/': {
      id: '/toDo/'
      path: '/toDo'
      fullPath: '/toDo'
      preLoaderRoute: typeof ToDoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizStart/': {
      id: '/quizStart/'
      path: '/quizStart'
      fullPath: '/quizStart'
      preLoaderRoute: typeof QuizStartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$imageId': {
      id: '/gallery/$imageId'
      path: '/gallery/$imageId'
      fullPath: '/gallery/$imageId'
      preLoaderRoute: typeof GalleryImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryImageIdRoute: GalleryImageIdRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  GameIndexRoute: GameIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  QuizStartIndexRoute: QuizStartIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ToDoIndexRoute: ToDoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
